### ISSUE TITLE
When 'R <1024|S|' are the 6 bit hll counts still needed?

### ISSUE THREAD

**Issue by kportertx** [yunwilliamyu/hyperminhash#1]
https://github.com/yunwilliamyu/hyperminhash/blob/5d88ff4796d08ff6043bd16dd2bc1b5ad727cd81/hyperminhash.py#L177

**Comment by yunwilliamyu** [comment]
Strictly speaking, this code is a combination of 3 estimators. There are two different estimators within hll_estimator, one for small cardinalities and one for large cardinalities. However, some experimentation showed that for much larger cardinalities a minhash-style estimator actually gives slightly better predictions, which is why I have this logic in place.

You could for example always use the hll_estimator. Or, alternately, you could always use a minhash-style estimator. You'll just get slightly worse accuracies.

**Comment by kportertx** [comment]
Thank you.
